const location = [
    "Agincourt",
    "Albert Campbell",
    "Albion",
    "Alderwood",
    "Amesbury Park",
    "Annette Street",
    "Armour Heights",
    "Barbara Frum",
    "Bayview",
    "Beaches",
    "Bendale",
    "Black Creek",
    "Bloor/Gladstone",
    "Brentwood",
    "Bridlewood",
    "Brookbanks",
    "Burrows Hall",
    "Cedarbrae",
    "Centennial",
    "City Hall",
    "Cliffcrest",
    "College/Shaw",
    "Danforth/Coxwell",
    "Davenport",
    "Dawes Road",
    "Deer Park",
    "Don Mills",
    "Downsview",
    "Dufferin/St. Clair",
    "Eatonville",
    "Eglinton Square",
    "Elmbrook Park",
    "Evelyn Gregory",
    "Fairview",
    "Flemingdon Park",
    "Forest Hill",
    "Fort York",
    "Gerrard/Ashdale",
    "Goldhawk Park",
    "High Park",
    "Highland Creek",
    "Hillcrest",
    "Humber Bay",
    "Humber Summit",
    "Humberwood",
    "Jane/Dundas",
    "Jane/Sheppard",
    "Jones",
    "Kennedy/Eglinton",
    "Leaside",
    "Lillian H. Smith",
    "Locke",
    "Long Branch",
    "Main Street",
    "Malvern",
    "Maria A. Shchuka",
    "Maryvale",
    "McGregor Park",
    "Mimico Centennial",
    "Morningside",
    "Mount Dennis",
    "Mount Pleasant",
    "New Toronto",
    "North York Central Library",
    "Northern District",
    "Northern Elms",
    "Oakwood Village Library and Arts Centre",
    "Palmerston",
    "Pape/Danforth",
    "Parkdale",
    "Parliament Street",
    "Perth/Dupont",
    "Pleasant View",
    "Port Union",
    "Queen/Saulter",
    "Rexdale",
    "Richview",
    "Riverdale",
    "Runnymede",
    "S. Walter Stewart",
    "Sanderson",
    "Scarborough Civic Centre",
    "Spadina Road",
    "St. James Town",
    "St. Lawrence",
    "Swansea Memorial",
    "Taylor Memorial",
    "Thorncliffe",
    "Toronto Reference Library",
    "Victoria Village",
    "Weston",
    "Woodside Square",
    "Woodview Park",
    "York Woods",
    "Yorkville",
    ]

    export default location;