source 'https://rubygems.org'


gem 'coffee-rails', '~> 4.1.0'
gem 'pg', '~> 0.15'
gem 'rails', '4.2.10'
gem 'sass-rails', '~> 5.0'
gem 'therubyracer', platforms: :ruby
gem 'uglifier', '>= 1.3.0'

gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'turbolinks'

gem 'puma'


group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'

  gem 'spring'
end

